name: 'FTP File Upload'
description: 'Upload a file to FTP.'
author: 'TomasBkk'
branding:
  icon: arrow-up-circle
  color: green
inputs:
  user:
    description: 'FTP User'
    required: true
  password:
    description: 'FTP Password'
    required: true
  host:
    description: 'FTP Hostname'
    required: true
  port:
    description: 'FTP Hostname'
    required: false
    default: '21'
  src:
    description: 'Path to file to upload'
    required: true
  dest:
    description: 'Destination file path on remote FTP'
    required: true
  secure:
    description: '(boolean | "implicit") Explicit FTPS over TLS, default: false. Use "implicit" if you need support for legacy implicit FTPS.'
    required: false
  rejectUnauthorized:
    description: 'Default is true. If false will allow unauthorized servers when using secure mode (such as servers using self-signed certificates)'
    required: false
    default: 'true'
  verbose:
    description: 'Default is false. If true verbose logging is used to debug the ftp connection and upload.'
    required: false
runs:
  using: 'node16'
  main: 'index.js'

